name: craigslist
description: A Craigslist application for the modern age.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+9
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  amplify_flutter: ^0.4.0
  amplify_datastore: ^0.4.0
  amplify_api: ^0.4.0
  amplify_analytics_pinpoint: ^0.4.5
  amplify_auth_cognito: ^0.4.0
  amplify_storage_s3: ^0.4.0
  intl: ^0.17.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  flutter_login: ^3.2.0
  amplify_authenticator: ^0.1.0  
  cached_network_image: ^3.2.0
  dropdown_button2: ^1.4.0

  
dev_dependencies:
  # For testing widgets
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # Added for testing framework. Current stable version compatible with our project.
  test: ^1.19.5

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
