name: Flutter Craigslist CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build appbundle